### ISSUE TITLE
macOS 13 Ventura - outPutFeed failure

### ISSUE THREAD

**Issue by FoUStep** [edasque/RSSs_Ubersicht_Widget#5]
<img width="996" alt="Screenshot 2022-10-24 at 23 22 17" src="https://user-images.githubusercontent.com/14996435/197632051-a0886433-bb94-4c22-9271-2fb3b9e6593a.png">

For some reason the outPutFeed doesn't load the RSS feed well. Resulting in a error in the debug log. Unsure how to fix this.

**Comment by edasque** [comment]
Want to try to get the code from the develop branch (https://github.com/edasque/RSSs_Ubersicht_Widget/tree/develop) to see if that fixes it?

Incidentally, are you on M1/M2 or Intel?

Also, from the Ubersicht Widget directory (with the RSSs.widget directory in it), what happens if you run ```RSSs-Widget/RSSs.widget/src/outputFeed``` in a terminal?

**Comment by FoUStep** [comment]
I'm on Intel (2020 MBP). The develop branch outPutfeed replacement really did the trick and fixed the issue.

Result from running from Terminal:
`/Users/FoUStep/Library/Application\ Support/Übersicht/widgets/RSSs-Widget/RSSs.widget/src/outputFeed ; exit;
[1]    16630 killed `
